name: Build Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate bot token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BUILD_BOT_ID }}
          private-key: ${{ secrets.BUILD_BOT_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name "pond-ink-build-bot[bot]"
          git config --global user.email "pond-ink-build-bot[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}.git
          git checkout -B build

      - name: Create placeholder js file
        run: |
          mkdir -p dist
          touch dist/ex124oj.user.js
          git add -f dist/ex124oj.user.js
          git diff --cached --quiet || git commit -m "User script generating prepared"

      - name: Build production js file
        run: |
          npm run build
          git add -f dist/ex124oj.user.js
          git diff --cached --quiet || git commit -m "User script generating completed"

      - name: Push to GitHub
        run: |
          git push -f origin build